### ISSUE TITLE
Knowledge sharing completes incomplete research

### ISSUE THREAD

**Issue by Encharrion** [Rongmario/Knowledge-Sharing#1]
When you share research, any research that was clicked on but not completed will be shared to the other player as fully completed research. The other player can then click on all newly unlocked research and then share back, which causes all the newly unlocked research to be shared back to the first player fully completed, and so on. This can be used to unlock all visible research without completing the requirements of a single one.

I believe that the knowledge share is not respecting research stages, as when you click on a new research page it is set as completed to its earliest stage (can't remember if that is stage 0 or stage 1). The research is then advanced a stage for each step completed. It would appear that Knowledge Sharing is granting all research unlocked regardless of stage.

EDIT: on FTB Interactions.

**Comment by Rongmario** [comment]
Thanks for the issue, have a vague idea of why this is happening. I'll check when I'm able to.

**Comment by Rongmario** [comment]
Fixed. [Next build being approved.](https://minecraft.curseforge.com/projects/knowledge-sharer/files/2710957)

Though a small client sync issue is introduced, but no biggie, I'll delve deeper into the source to see if there's another way I can do this but this is okay for now.
